# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 140b2c5aa691c4c5f151861220ec08e28bd2d1f44cb8bd609a5c1823487687bbd9f1d0ca2baeaef3ee33295ca73bf7853f9129b737bceb37f588953d4f1239cb

test:
  secret_key_base: b34c0c5f46709488c89561827bddaf6dbd57adc382c35c611b7b5151edeb04a3150dd8af407e1ebb0eea9799c9ee5c36c19baee4fbb2fbc6de1369bf13657471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
