class RootController < ApplicationController
  ICON_NAMES = %w(
    tmix-angle-up-down
    tmix-animal
    tmix-apron
    tmix-art
    tmix-baby
    tmix-back-layer
    tmix-back
    tmix-bag
    tmix-basic
    tmix-bottom-alignment
    tmix-cancel
    tmix-cart
    tmix-decoration-text
    tmix-design
    tmix-equal
    tmix-event
    tmix-file-text-with-pen
    tmix-first-layer
    tmix-font
    tmix-food
    tmix-frame
    tmix-free-dial
    tmix-front-layer
    tmix-gift
    tmix-horizontal-center-alignment
    tmix-horizontal
    tmix-ink
    tmix-japan
    tmix-kids
    tmix-ladies-tshirt
    tmix-last-layer
    tmix-layer
    tmix-left-alignment
    tmix-line-a
    tmix-lock
    tmix-logo-heart
    tmix-long-tshirt
    tmix-marine
    tmix-music
    tmix-outline
    tmix-paint
    tmix-parka
    tmix-pc
    tmix-plant
    tmix-poloshirt
    tmix-present
    tmix-print-area-apron
    tmix-print-area-baby-back
    tmix-print-area-baby-front
    tmix-print-area-bag
    tmix-print-area-clutch-back
    tmix-print-area-clutch-front
    tmix-print-area-handtowel
    tmix-print-area-long-tshirt-back
    tmix-print-area-long-tshirt-front
    tmix-print-area-poloshirt-back
    tmix-print-area-poloshirt-front
    tmix-print-area-pouch-back
    tmix-print-area-pouch-front
    tmix-print-area-pull-parka-back
    tmix-print-area-pull-parka-front
    tmix-print-area-towel-left
    tmix-print-area-towel-right
    tmix-print-area-tshirt-back
    tmix-print-area-tshirt-front
    tmix-print-area-zipup-parka-back
    tmix-print-area-zipup-parka-front
    tmix-processing
    tmix-rank-1st
    tmix-rank-2nd
    tmix-rank-3rd
    tmix-rank
    tmix-redo
    tmix-right-alignment
    tmix-rock
    tmix-scene
    tmix-shadow
    tmix-sport
    tmix-stamp
    tmix-sweat
    tmix-symbol
    tmix-tag
    tmix-text
    tmix-tmix-heart
    tmix-tmix-logo
    tmix-top-alignment
    tmix-towel
    tmix-truck
    tmix-tshirt
    tmix-undo
    tmix-unlock
    tmix-upload
    tmix-user
    tmix-vertical-center-alignment
    tmix-vertical
    tmix-zoom
  )
  def index
    @icons = ICON_NAMES
  end
end
